[versions]
procyon = "0.6.0"
teavm = "0.14.0-SNAPSHOT"

[libraries]
procyon-compilertools = { group = "org.bitbucket.mstrobel", name = "procyon-compilertools", version.ref = "procyon" }
teavm-core = { group = "org.teavm", name = "teavm-core", version.ref = "teavm" }

[plugins]
teavm = { id = "org.teavm", version.ref = "teavm" }
blossom = { id = "net.kyori.blossom", version = "2.1.0" }
